image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  _PHP_VERSION: "7.1"

build:
  stage: build
  script:
    - docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
    - docker build --rm -t corycollier/apache-php:$CI_BUILD_REF_NAME .
    - docker push corycollier/apache-php:$CI_BUILD_REF_NAME

test:
    stage: test
    script:
      - apk add --update wget bash
      - docker run -itd --name $CI_BUILD_REF_NAME corycollier/apache-php:$CI_BUILD_REF_NAME
      - ls -alih tests/
      - bash ./tests/apache-modules-test.sh $CI_BUILD_REF_NAME
      - bash ./tests/apache-docroot-test.sh $CI_BUILD_REF_NAME
      - bash ./tests/php-version-test.sh $CI_BUILD_REF_NAME $_PHP_VERSION
      - bash ./tests/php-modules-test.sh $CI_BUILD_REF_NAME
      - bash ./tests/php-composer-test.sh $CI_BUILD_REF_NAME
      - bash ./tests/system-git-test.sh $CI_BUILD_REF_NAME
      - bash ./tests/system-sendmail-test.sh $CI_BUILD_REF_NAME
      - bash ./tests/system-cron-test.sh $CI_BUILD_REF_NAME
