image: docker:latest

services:
  - docker:dind

before_script:
  - docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"

stages:
  - build

build:
  stage: build
  script:
    - docker build --rm -t corycollier/apache-php:$CI_COMMIT_TAG
    - docker push corycollier/apache-php:$CI_COMMIT_TAG
  only:
    - tags
