image: docker:latest

services:
  - docker:dind

stages:
  - build

build:tags:
  stage: build
  script:
    - docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
    - docker build --rm -t corycollier/apache-php:$CI_COMMIT_TAG .
    - docker push corycollier/apache-php:$CI_COMMIT_TAG
  only:
    - tags

build:latest:
  stage: build
  script:
    - docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
    - docker build --rm -t corycollier/apache-php .
    - docker push corycollier/apache-php
  only:
    - master
    - develop

build:nightly:
  stage: build
  script:
    - docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
    - docker build --rm -t corycollier/apache-php:$PHP_VERSION .
    - docker push corycollier/apache-php:$PHP_VERSION
  only:
    - 5.6.x
    - 7.0.x
    - 7.1.x
