image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
    - docker build --rm -t corycollier/apache-php:$CI_BUILD_REF_NAME .
    - docker push corycollier/apache-php:$CI_BUILD_REF_NAME

test:
    stage: test
    script:
      - apk add --update wget bash
      - docker run -itd --name $CI_BUILD_REF_NAME corycollier/apache-php:$CI_BUILD_REF_NAME
      - ls -alih
      - bash ./tests/php-version.sh

# - >
#             docker run -itd -P
#             --volume $MOUNTED_PATH/$CI_COMMIT_REF_SLUG:$DOCKER_PATH
#             --env VIRTUAL_HOST="$CI_COMMIT_REF_SLUG-$FQDN"
#             --add-host database.local:172.31.39.8
#             --name $CI_COMMIT_REF_SLUG-$FQDN
#             corycollier/apache-php:7.1-zf1.12-dev
