stages:
    - build
    - deploy

build:tags:
    script:
        - docker build --rm -t corycollier/apache-php:$CI_COMMIT_TAG
        - docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
        - docker push corycollier/apache-php:$CI_COMMIT_TAG
    only:
        - tags
    
