image: docker:latest

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
    - docker build --rm -t corycollier/npm-php:10.x-7.1 .
    - docker push corycollier/apache-php:$CI_COMMIT_TAG
  only:
    - tags
