image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker login --username="$DOCKER_USER" --password="$DOCKER_PASS"
    - docker build --rm -t corycollier/apache-php:$CI_BUILD_REF_NAME .
    - docker push corycollier/apache-php:$CI_BUILD_REF_NAME

test:
    stage: test
    script:
      - docker run -itd --name $CI_BUILD_REF_NAME corycollier/apache-php:$CI_BUILD_REF_NAME
      - if [[ $(docker exec $CI_BUILD_REF_NAME bash -c "php -v | sed -n '/PHP [0-9].[0-9]/p'" | awk '{ print $2 }') =~ "7.3"* ]]; then echo "good"; else exit 1; fi
